name: lost_and_found_app
description: A world-class Lost & Found platform with commercialization and country-based data segregation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  image_picker: ^1.0.7
  file_selector: ^1.0.3
  file_selector_platform_interface: ^2.6.0
  file_selector_windows: ^0.9.3
  go_router: ^14.8.1
  path_provider: ^2.1.2
  uuid: ^4.5.1
  cached_network_image: ^3.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  # firebase_core: ^3.6.0
  # firebase_auth: ^5.3.1
  # cloud_firestore: ^5.4.4
  # firebase_storage: ^12.3.2
  # google_mobile_ads: ^5.2.0
  # stripe_payment: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_cat.png
    - assets/default_documents.png
    - assets/default_dog.png
    - assets/default_driver_license.png
    - assets/default_electronic_card.png
    - assets/default_general_goods.png
    - assets/default_household_goods.png
    - assets/default_id_card.png
    - assets/default_keys.png
    - assets/default_laguage.png
    - assets/default_livestock.png
    - assets/default_missing_person.png
    - assets/default_passport.png
    - assets/default_pets.png
    - assets/default_phones.png
    - assets/default_wallet.png
    - assets/default_wated.png
  generate: true 